# Generated by Django 5.1.5 on 2025-04-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "application",
            "0002_cart_cartitem_drink_order_orderitem_pizza_pizzaprice_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="topping",
            name="icon",
            field=models.CharField(default="", max_length=50),
        ),
    ]
