# Generated by Django 5.1.5 on 2025-05-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0003_topping_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="topping",
            name="base_price",
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=6),
        ),
    ]
