# Generated by Django 5.1.5 on 2025-06-01 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0004_topping_base_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="drink",
            name="available",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="pizza",
            name="available",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="drink",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="application.drink",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="pizza",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="application.pizzaprice",
            ),
        ),
    ]
