# Generated by Django 5.1.5 on 2025-06-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "application",
            "0005_drink_available_pizza_available_alter_cartitem_drink_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="size",
            name="multiplier",
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6),
        ),
    ]
