# Generated by Django 5.1.5 on 2025-06-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0006_size_multiplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="size",
            name="description",
            field=models.CharField(default="", max_length=50),
        ),
    ]
