# Generated by Django 5.1.5 on 2025-06-02 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0007_size_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pizza",
            old_name="available_toppings",
            new_name="toppings",
        ),
    ]
