# Generated by Django 5.1.5 on 2025-06-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0008_rename_available_toppings_pizza_toppings"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("received", "Received"),
                    ("in_progress", "In progress"),
                    ("completed", "Completed"),
                ],
                db_index=True,
                default="received",
                max_length=20,
            ),
        ),
    ]
